### ISSUE TITLE
Sipping queries 

### ISSUE THREAD

**Issue by filiptronicek** [czM1K3/prisma-redis#4]
I would really appreciate if one could skip some methods so they wouldn't be cached (e.g., I would like to skip `findMany`), instead of just specifying the ones which **should** be cached.

**Comment by czM1K3** [comment]
Answer is on [this](https://github.com/czM1K3/prisma-redis/blob/7414303f99cab911c9c0fcc0300e6b8f78b62d3d/README.md?plain=1#L30) line. :D

**Comment by filiptronicek** [comment]
@czM1K3 can I instead of including just exclude some (make a blacklist)?

**Comment by czM1K3** [comment]
Added in: [01130bc](https://github.com/czM1K3/prisma-redis/commit/01130bc39a6ed4b56818e76b3d6826bcdcf7d8e7)

**Comment by filiptronicek** [comment]
Pog
